version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-server
    ports:
      - "5672:5672"   # Default RabbitMQ port
      - "15672:15672" # Management UI port (Browser ကနေ ဝင်ကြည့်လို့ရမယ့် port)

  service-1:
    build: ./service-1-publisher
    container_name: service-1-express
    ports:
      - "3001:3001"
    depends_on:
      - rabbitmq

  service-2:
    build: ./service-2-hono
    container_name: service-2-hono
    ports:
      - "3002:3002"
    depends_on:
      - rabbitmq

  service-3:
    build: ./service-3-express
    container_name: service-3-express
    ports:
      - "3003:3003"
    depends_on:
      - rabbitmq