version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"

  service-1:
    build: ./service-1-publisher
    container_name: service-1-express
    ports:
      - "3001:3001"
    volumes:
      - ./service-1-publisher:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  service-2:
    build: ./service-2-hono
    container_name: service-2-hono
    ports:
      - "3002:3002"
    volumes:
      - ./service-2-hono:/app
      - /app/node_modules
    depends_on:
      - rabbitmq

  service-3:
    build: ./service-3-express
    container_name: service-3-express
    ports:
      - "3003:3003"
    volumes:
      - ./service-3-express:/app
      - /app/node_modules
    depends_on:
      - rabbitmq